### ISSUE TITLE
wrong package.json leads to no types found when node > 10

### ISSUE THREAD

**Issue by loynoir** [martinheidegger/ip-codec#1]
https://arethetypeswrong.github.io/?p=%40leichtgewicht%2Fip-codec%402.0.4

  | "@leichtgewicht/ip-codec"
-- | --
node10 | ✅
node16 (from CJS) | ❌ No types
node16 (from ESM) | ❌ No types
bundler | ❌ No types

**Comment by angelxmoreno** [comment]
any progress on this?

**Comment by martinheidegger** [comment]
Published as 2.0.5
